# Generated by Django 2.1.5 on 2019-04-24 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record_Breakdown_Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(max_length=500)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit.Mohh')),
            ],
        ),
    ]
