# Generated by Django 2.1.5 on 2019-04-24 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mohh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('d', 'DumpTruck'), ('e', 'Excavator')], max_length=1)),
                ('date_assign', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='mohh',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit.Unit'),
        ),
    ]
